//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class AidiFactoryRunner : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AidiFactoryRunner(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AidiFactoryRunner obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AidiFactoryRunner() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_AidiFactoryRunner(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public AidiFactoryRunner(string check_code) : this(csharpaidiclientPINVOKE.new_AidiFactoryRunner__SWIG_0(check_code), true) {
    if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
  }

  public AidiFactoryRunner() : this(csharpaidiclientPINVOKE.new_AidiFactoryRunner__SWIG_1(), true) {
  }

  public void set_param(FactoryClientParamWrapper param) {
    csharpaidiclientPINVOKE.AidiFactoryRunner_set_param(swigCPtr, FactoryClientParamWrapper.getCPtr(param));
    if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
  }

  public void start() {
    csharpaidiclientPINVOKE.AidiFactoryRunner_start(swigCPtr);
  }

  public void release() {
    csharpaidiclientPINVOKE.AidiFactoryRunner_release(swigCPtr);
  }

  public void set_batch_size(IntVector batch_size) {
    csharpaidiclientPINVOKE.AidiFactoryRunner_set_batch_size(swigCPtr, IntVector.getCPtr(batch_size));
    if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_test_batch_image(BatchAidiImage batch) {
    csharpaidiclientPINVOKE.AidiFactoryRunner_set_test_batch_image(swigCPtr, BatchAidiImage.getCPtr(batch));
    if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
  }

  public StringVector get_detect_result() {
    StringVector ret = new StringVector(csharpaidiclientPINVOKE.AidiFactoryRunner_get_detect_result(swigCPtr), true);
    return ret;
  }

}

}
