//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class AIDIEntrance : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AIDIEntrance(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AIDIEntrance obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AIDIEntrance() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_AIDIEntrance(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public AIDIEntrance() : this(csharpaidiclientPINVOKE.new_AIDIEntrance(), true) {
  }

  public void set_model_root(string root_path) {
    csharpaidiclientPINVOKE.AIDIEntrance_set_model_root(swigCPtr, root_path);
    if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
  }

  public void initialize() {
    csharpaidiclientPINVOKE.AIDIEntrance_initialize__SWIG_0(swigCPtr);
  }

  public void initialize(bool use_gpu, int device_num) {
    csharpaidiclientPINVOKE.AIDIEntrance_initialize__SWIG_1(swigCPtr, use_gpu, device_num);
  }

  public string entrance_test_image(AidiImage image) {
    string ret = csharpaidiclientPINVOKE.AIDIEntrance_entrance_test_image(swigCPtr, AidiImage.getCPtr(image));
    if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
