//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class ClassifyClientParamWrapper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ClassifyClientParamWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ClassifyClientParamWrapper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ClassifyClientParamWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_ClassifyClientParamWrapper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int batch_size {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_batch_size_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_batch_size_get(swigCPtr);
      return ret;
    } 
  }

  public bool use_gpu {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_use_gpu_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_use_gpu_get(swigCPtr);
      return ret;
    } 
  }

  public int device_number {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_device_number_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_device_number_get(swigCPtr);
      return ret;
    } 
  }

  public string save_model_path {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_save_model_path_set(swigCPtr, value);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_save_model_path_get(swigCPtr);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool use_runtime {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_use_runtime_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_use_runtime_get(swigCPtr);
      return ret;
    } 
  }

  public bool encrypt {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_encrypt_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_encrypt_get(swigCPtr);
      return ret;
    } 
  }

  public string model_path {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_model_path_set(swigCPtr, value);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_model_path_get(swigCPtr);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool force_set_gpu {
    set {
      csharpaidiclientPINVOKE.ClassifyClientParamWrapper_force_set_gpu_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.ClassifyClientParamWrapper_force_set_gpu_get(swigCPtr);
      return ret;
    } 
  }

  public ClassifyClientParamWrapper() : this(csharpaidiclientPINVOKE.new_ClassifyClientParamWrapper(), true) {
  }

}

}
