//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

class csharpaidiclientPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="SWIGRegisterExceptionCallbacks_csharpaidiclient")]
    public static extern void SWIGRegisterExceptionCallbacks_csharpaidiclient(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_csharpaidiclient")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_csharpaidiclient(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_csharpaidiclient(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_csharpaidiclient(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(csharpaidiclientPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(csharpaidiclientPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="SWIGRegisterStringCallback_csharpaidiclient")]
    public static extern void SWIGRegisterStringCallback_csharpaidiclient(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_csharpaidiclient(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static csharpaidiclientPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Clear___")]
  public static extern void IntVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Add___")]
  public static extern void IntVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_size___")]
  public static extern uint IntVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_capacity___")]
  public static extern uint IntVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_reserve___")]
  public static extern void IntVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_IntVector__SWIG_0___")]
  public static extern global::System.IntPtr new_IntVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_IntVector__SWIG_1___")]
  public static extern global::System.IntPtr new_IntVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_IntVector__SWIG_2___")]
  public static extern global::System.IntPtr new_IntVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_getitemcopy___")]
  public static extern int IntVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_getitem___")]
  public static extern int IntVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_setitem___")]
  public static extern void IntVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_AddRange___")]
  public static extern void IntVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_GetRange___")]
  public static extern global::System.IntPtr IntVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Insert___")]
  public static extern void IntVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_InsertRange___")]
  public static extern void IntVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_RemoveAt___")]
  public static extern void IntVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_RemoveRange___")]
  public static extern void IntVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Repeat___")]
  public static extern global::System.IntPtr IntVector_Repeat(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Reverse__SWIG_0___")]
  public static extern void IntVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Reverse__SWIG_1___")]
  public static extern void IntVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_SetRange___")]
  public static extern void IntVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Contains___")]
  public static extern bool IntVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_IndexOf___")]
  public static extern int IntVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_LastIndexOf___")]
  public static extern int IntVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_IntVector_Remove___")]
  public static extern bool IntVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_IntVector___")]
  public static extern void delete_IntVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Clear___")]
  public static extern void FloatVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Add___")]
  public static extern void FloatVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_size___")]
  public static extern uint FloatVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_capacity___")]
  public static extern uint FloatVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_reserve___")]
  public static extern void FloatVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_FloatVector__SWIG_0___")]
  public static extern global::System.IntPtr new_FloatVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_FloatVector__SWIG_1___")]
  public static extern global::System.IntPtr new_FloatVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_FloatVector__SWIG_2___")]
  public static extern global::System.IntPtr new_FloatVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_getitemcopy___")]
  public static extern float FloatVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_getitem___")]
  public static extern float FloatVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_setitem___")]
  public static extern void FloatVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_AddRange___")]
  public static extern void FloatVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_GetRange___")]
  public static extern global::System.IntPtr FloatVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Insert___")]
  public static extern void FloatVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_InsertRange___")]
  public static extern void FloatVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_RemoveAt___")]
  public static extern void FloatVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_RemoveRange___")]
  public static extern void FloatVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Repeat___")]
  public static extern global::System.IntPtr FloatVector_Repeat(float jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Reverse__SWIG_0___")]
  public static extern void FloatVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Reverse__SWIG_1___")]
  public static extern void FloatVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_SetRange___")]
  public static extern void FloatVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Contains___")]
  public static extern bool FloatVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_IndexOf___")]
  public static extern int FloatVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_LastIndexOf___")]
  public static extern int FloatVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FloatVector_Remove___")]
  public static extern bool FloatVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_FloatVector___")]
  public static extern void delete_FloatVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Clear___")]
  public static extern void StringVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Add___")]
  public static extern void StringVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_size___")]
  public static extern uint StringVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_capacity___")]
  public static extern uint StringVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_reserve___")]
  public static extern void StringVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_StringVector__SWIG_0___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_StringVector__SWIG_1___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_StringVector__SWIG_2___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_getitemcopy___")]
  public static extern string StringVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_getitem___")]
  public static extern string StringVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_setitem___")]
  public static extern void StringVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_AddRange___")]
  public static extern void StringVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_GetRange___")]
  public static extern global::System.IntPtr StringVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Insert___")]
  public static extern void StringVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_InsertRange___")]
  public static extern void StringVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_RemoveAt___")]
  public static extern void StringVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_RemoveRange___")]
  public static extern void StringVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Repeat___")]
  public static extern global::System.IntPtr StringVector_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Reverse__SWIG_0___")]
  public static extern void StringVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Reverse__SWIG_1___")]
  public static extern void StringVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_SetRange___")]
  public static extern void StringVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Contains___")]
  public static extern bool StringVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_IndexOf___")]
  public static extern int StringVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_LastIndexOf___")]
  public static extern int StringVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringVector_Remove___")]
  public static extern bool StringVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_StringVector___")]
  public static extern void delete_StringVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_StringIntMap__SWIG_0___")]
  public static extern global::System.IntPtr new_StringIntMap__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_StringIntMap__SWIG_1___")]
  public static extern global::System.IntPtr new_StringIntMap__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_size___")]
  public static extern uint StringIntMap_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_empty___")]
  public static extern bool StringIntMap_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_Clear___")]
  public static extern void StringIntMap_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_getitem___")]
  public static extern int StringIntMap_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_setitem___")]
  public static extern void StringIntMap_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_ContainsKey___")]
  public static extern bool StringIntMap_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_Add___")]
  public static extern void StringIntMap_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_Remove___")]
  public static extern bool StringIntMap_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_create_iterator_begin___")]
  public static extern global::System.IntPtr StringIntMap_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_get_next_key___")]
  public static extern string StringIntMap_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_StringIntMap_destroy_iterator___")]
  public static extern void StringIntMap_destroy_iterator(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_StringIntMap___")]
  public static extern void delete_StringIntMap(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiImage___")]
  public static extern global::System.IntPtr new_AidiImage();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AidiImage___")]
  public static extern void delete_AidiImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_get_mat___")]
  public static extern void AidiImage_get_mat(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_get_mat_const___")]
  public static extern global::System.IntPtr AidiImage_get_mat_const(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_empty___")]
  public static extern bool AidiImage_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_set_mat___")]
  public static extern void AidiImage_set_mat(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_data_byte_size___")]
  public static extern int AidiImage_data_byte_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_width___")]
  public static extern int AidiImage_width(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_height___")]
  public static extern int AidiImage_height(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_channel___")]
  public static extern int AidiImage_channel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_char_ptr_to_mat___")]
  public static extern void AidiImage_char_ptr_to_mat(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.Out, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_mat_to_char_ptr___")]
  public static extern void AidiImage_mat_to_char_ptr(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.Out, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_vector_int_to_mat___")]
  public static extern void AidiImage_vector_int_to_mat(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_vector_float_to_mat___")]
  public static extern void AidiImage_vector_float_to_mat(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_mat_to_vector_float___")]
  public static extern void AidiImage_mat_to_vector_float(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_mat_to_vector_int___")]
  public static extern void AidiImage_mat_to_vector_int(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_read_image__SWIG_0___")]
  public static extern void AidiImage_read_image__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_read_image__SWIG_1___")]
  public static extern void AidiImage_read_image__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_show_image___")]
  public static extern void AidiImage_show_image(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_draw_result___")]
  public static extern bool AidiImage_draw_result(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiImage_save_image___")]
  public static extern void AidiImage_save_image(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_BatchAidiImage___")]
  public static extern global::System.IntPtr new_BatchAidiImage();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_BatchAidiImage___")]
  public static extern void delete_BatchAidiImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_BatchAidiImage_add_image___")]
  public static extern void BatchAidiImage_add_image(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_BatchAidiImage_clear_images___")]
  public static extern void BatchAidiImage_clear_images(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_BatchAidiImage_show_all_images___")]
  public static extern void BatchAidiImage_show_all_images(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_BatchAidiImage_get_images_size___")]
  public static extern int BatchAidiImage_get_images_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_BatchAidiImage_get_all_images___")]
  public static extern void BatchAidiImage_get_all_images(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_BatchAidiImage_at___")]
  public static extern global::System.IntPtr BatchAidiImage_at(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_save_model_path_list_set___")]
  public static extern void FactoryClientParamWrapper_save_model_path_list_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_save_model_path_list_get___")]
  public static extern global::System.IntPtr FactoryClientParamWrapper_save_model_path_list_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_operator_name_list_set___")]
  public static extern void FactoryClientParamWrapper_operator_name_list_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_operator_name_list_get___")]
  public static extern global::System.IntPtr FactoryClientParamWrapper_operator_name_list_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_operator_type_list_set___")]
  public static extern void FactoryClientParamWrapper_operator_type_list_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_operator_type_list_get___")]
  public static extern global::System.IntPtr FactoryClientParamWrapper_operator_type_list_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_device_number_set___")]
  public static extern void FactoryClientParamWrapper_device_number_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_device_number_get___")]
  public static extern int FactoryClientParamWrapper_device_number_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_use_gpu_set___")]
  public static extern void FactoryClientParamWrapper_use_gpu_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_use_gpu_get___")]
  public static extern bool FactoryClientParamWrapper_use_gpu_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_use_runtime_set___")]
  public static extern void FactoryClientParamWrapper_use_runtime_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FactoryClientParamWrapper_use_runtime_get___")]
  public static extern bool FactoryClientParamWrapper_use_runtime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_FactoryClientParamWrapper___")]
  public static extern global::System.IntPtr new_FactoryClientParamWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_FactoryClientParamWrapper___")]
  public static extern void delete_FactoryClientParamWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_batch_size_set___")]
  public static extern void ClassifyClientParamWrapper_batch_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_batch_size_get___")]
  public static extern int ClassifyClientParamWrapper_batch_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_use_gpu_set___")]
  public static extern void ClassifyClientParamWrapper_use_gpu_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_use_gpu_get___")]
  public static extern bool ClassifyClientParamWrapper_use_gpu_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_device_number_set___")]
  public static extern void ClassifyClientParamWrapper_device_number_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_device_number_get___")]
  public static extern int ClassifyClientParamWrapper_device_number_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_save_model_path_set___")]
  public static extern void ClassifyClientParamWrapper_save_model_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_save_model_path_get___")]
  public static extern string ClassifyClientParamWrapper_save_model_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_use_runtime_set___")]
  public static extern void ClassifyClientParamWrapper_use_runtime_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_use_runtime_get___")]
  public static extern bool ClassifyClientParamWrapper_use_runtime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_encrypt_set___")]
  public static extern void ClassifyClientParamWrapper_encrypt_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_encrypt_get___")]
  public static extern bool ClassifyClientParamWrapper_encrypt_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_model_path_set___")]
  public static extern void ClassifyClientParamWrapper_model_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_model_path_get___")]
  public static extern string ClassifyClientParamWrapper_model_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_force_set_gpu_set___")]
  public static extern void ClassifyClientParamWrapper_force_set_gpu_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyClientParamWrapper_force_set_gpu_get___")]
  public static extern bool ClassifyClientParamWrapper_force_set_gpu_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_ClassifyClientParamWrapper___")]
  public static extern global::System.IntPtr new_ClassifyClientParamWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_ClassifyClientParamWrapper___")]
  public static extern void delete_ClassifyClientParamWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_model_path_set___")]
  public static extern void LocationClientParamWrapper_model_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_model_path_get___")]
  public static extern string LocationClientParamWrapper_model_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_deploy_set___")]
  public static extern void LocationClientParamWrapper_deploy_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_deploy_get___")]
  public static extern string LocationClientParamWrapper_deploy_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_save_model_path_set___")]
  public static extern void LocationClientParamWrapper_save_model_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_save_model_path_get___")]
  public static extern string LocationClientParamWrapper_save_model_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_save_model_path_defined_set___")]
  public static extern void LocationClientParamWrapper_save_model_path_defined_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_save_model_path_defined_get___")]
  public static extern bool LocationClientParamWrapper_save_model_path_defined_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_w_set___")]
  public static extern void LocationClientParamWrapper_test_input_shape_w_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_w_get___")]
  public static extern int LocationClientParamWrapper_test_input_shape_w_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_h_set___")]
  public static extern void LocationClientParamWrapper_test_input_shape_h_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_h_get___")]
  public static extern int LocationClientParamWrapper_test_input_shape_h_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_c_set___")]
  public static extern void LocationClientParamWrapper_test_input_shape_c_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_c_get___")]
  public static extern int LocationClientParamWrapper_test_input_shape_c_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_set___")]
  public static extern void LocationClientParamWrapper_test_input_shape_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_input_shape_get___")]
  public static extern int LocationClientParamWrapper_test_input_shape_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_batch_size_set___")]
  public static extern void LocationClientParamWrapper_batch_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_batch_size_get___")]
  public static extern int LocationClientParamWrapper_batch_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_use_gpu_set___")]
  public static extern void LocationClientParamWrapper_use_gpu_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_use_gpu_get___")]
  public static extern bool LocationClientParamWrapper_use_gpu_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_device_number_set___")]
  public static extern void LocationClientParamWrapper_device_number_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_device_number_get___")]
  public static extern int LocationClientParamWrapper_device_number_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_model_initialized__set___")]
  public static extern void LocationClientParamWrapper_test_model_initialized__set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_test_model_initialized__get___")]
  public static extern bool LocationClientParamWrapper_test_model_initialized__get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_long_detection_set___")]
  public static extern void LocationClientParamWrapper_long_detection_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_long_detection_get___")]
  public static extern bool LocationClientParamWrapper_long_detection_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_split_set___")]
  public static extern void LocationClientParamWrapper_split_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_split_get___")]
  public static extern int LocationClientParamWrapper_split_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_split_w_set___")]
  public static extern void LocationClientParamWrapper_split_w_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_split_w_get___")]
  public static extern int LocationClientParamWrapper_split_w_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_split_h_set___")]
  public static extern void LocationClientParamWrapper_split_h_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_split_h_get___")]
  public static extern int LocationClientParamWrapper_split_h_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_encrypt_set___")]
  public static extern void LocationClientParamWrapper_encrypt_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_encrypt_get___")]
  public static extern bool LocationClientParamWrapper_encrypt_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_use_runtime_set___")]
  public static extern void LocationClientParamWrapper_use_runtime_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_use_runtime_get___")]
  public static extern bool LocationClientParamWrapper_use_runtime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_force_set_gpu_set___")]
  public static extern void LocationClientParamWrapper_force_set_gpu_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationClientParamWrapper_force_set_gpu_get___")]
  public static extern bool LocationClientParamWrapper_force_set_gpu_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_LocationClientParamWrapper___")]
  public static extern global::System.IntPtr new_LocationClientParamWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_LocationClientParamWrapper___")]
  public static extern void delete_LocationClientParamWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_device_number_set___")]
  public static extern void SegmentClientParamWrapper_device_number_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_device_number_get___")]
  public static extern int SegmentClientParamWrapper_device_number_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_use_gpu_set___")]
  public static extern void SegmentClientParamWrapper_use_gpu_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_use_gpu_get___")]
  public static extern bool SegmentClientParamWrapper_use_gpu_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_save_model_path_set___")]
  public static extern void SegmentClientParamWrapper_save_model_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_save_model_path_get___")]
  public static extern string SegmentClientParamWrapper_save_model_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_batch_size_set___")]
  public static extern void SegmentClientParamWrapper_batch_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_batch_size_get___")]
  public static extern int SegmentClientParamWrapper_batch_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_use_runtime_set___")]
  public static extern void SegmentClientParamWrapper_use_runtime_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_use_runtime_get___")]
  public static extern bool SegmentClientParamWrapper_use_runtime_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_encrypt_set___")]
  public static extern void SegmentClientParamWrapper_encrypt_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_encrypt_get___")]
  public static extern bool SegmentClientParamWrapper_encrypt_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_model_path_set___")]
  public static extern void SegmentClientParamWrapper_model_path_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_model_path_get___")]
  public static extern string SegmentClientParamWrapper_model_path_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_force_set_gpu_set___")]
  public static extern void SegmentClientParamWrapper_force_set_gpu_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_force_set_gpu_get___")]
  public static extern bool SegmentClientParamWrapper_force_set_gpu_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_use_filter_set___")]
  public static extern void SegmentClientParamWrapper_use_filter_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_SegmentClientParamWrapper_use_filter_get___")]
  public static extern bool SegmentClientParamWrapper_use_filter_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_SegmentClientParamWrapper___")]
  public static extern global::System.IntPtr new_SegmentClientParamWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_SegmentClientParamWrapper___")]
  public static extern void delete_SegmentClientParamWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_mAP_set___")]
  public static extern void LocationResultWrapper_mAP_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_mAP_get___")]
  public static extern double LocationResultWrapper_mAP_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_recall_set___")]
  public static extern void LocationResultWrapper_recall_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_recall_get___")]
  public static extern double LocationResultWrapper_recall_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_all_gt_num_set___")]
  public static extern void LocationResultWrapper_all_gt_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_all_gt_num_get___")]
  public static extern int LocationResultWrapper_all_gt_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_all_pred_num_set___")]
  public static extern void LocationResultWrapper_all_pred_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_all_pred_num_get___")]
  public static extern int LocationResultWrapper_all_pred_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_recall_num_set___")]
  public static extern void LocationResultWrapper_recall_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_recall_num_get___")]
  public static extern int LocationResultWrapper_recall_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_precise_num_set___")]
  public static extern void LocationResultWrapper_precise_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_LocationResultWrapper_precise_num_get___")]
  public static extern int LocationResultWrapper_precise_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_LocationResultWrapper___")]
  public static extern global::System.IntPtr new_LocationResultWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_LocationResultWrapper___")]
  public static extern void delete_LocationResultWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_recall_set___")]
  public static extern void DefectDetectResultWrapper_recall_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_recall_get___")]
  public static extern double DefectDetectResultWrapper_recall_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_ap_set___")]
  public static extern void DefectDetectResultWrapper_ap_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_ap_get___")]
  public static extern double DefectDetectResultWrapper_ap_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_center_recall_set___")]
  public static extern void DefectDetectResultWrapper_center_recall_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_center_recall_get___")]
  public static extern double DefectDetectResultWrapper_center_recall_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_center_ap_set___")]
  public static extern void DefectDetectResultWrapper_center_ap_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_center_ap_get___")]
  public static extern double DefectDetectResultWrapper_center_ap_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_all_gt_num_set___")]
  public static extern void DefectDetectResultWrapper_all_gt_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_all_gt_num_get___")]
  public static extern long DefectDetectResultWrapper_all_gt_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_recall_num_set___")]
  public static extern void DefectDetectResultWrapper_recall_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_recall_num_get___")]
  public static extern long DefectDetectResultWrapper_recall_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_all_center_num_set___")]
  public static extern void DefectDetectResultWrapper_all_center_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_all_center_num_get___")]
  public static extern long DefectDetectResultWrapper_all_center_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_center_recall_num_set___")]
  public static extern void DefectDetectResultWrapper_center_recall_num_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_DefectDetectResultWrapper_center_recall_num_get___")]
  public static extern long DefectDetectResultWrapper_center_recall_num_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_DefectDetectResultWrapper___")]
  public static extern global::System.IntPtr new_DefectDetectResultWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_DefectDetectResultWrapper___")]
  public static extern void delete_DefectDetectResultWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyResultWrapper_acc_set___")]
  public static extern void ClassifyResultWrapper_acc_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyResultWrapper_acc_get___")]
  public static extern double ClassifyResultWrapper_acc_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyResultWrapper_recall_set___")]
  public static extern void ClassifyResultWrapper_recall_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_ClassifyResultWrapper_recall_get___")]
  public static extern double ClassifyResultWrapper_recall_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_ClassifyResultWrapper___")]
  public static extern global::System.IntPtr new_ClassifyResultWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_ClassifyResultWrapper___")]
  public static extern void delete_ClassifyResultWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_ap_set___")]
  public static extern void FeatureLocationResultWrapper_ap_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_ap_get___")]
  public static extern double FeatureLocationResultWrapper_ap_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_recall_set___")]
  public static extern void FeatureLocationResultWrapper_recall_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_recall_get___")]
  public static extern double FeatureLocationResultWrapper_recall_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_position_ap_set___")]
  public static extern void FeatureLocationResultWrapper_position_ap_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_position_ap_get___")]
  public static extern double FeatureLocationResultWrapper_position_ap_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_position_recall_set___")]
  public static extern void FeatureLocationResultWrapper_position_recall_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_FeatureLocationResultWrapper_position_recall_get___")]
  public static extern double FeatureLocationResultWrapper_position_recall_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_FeatureLocationResultWrapper___")]
  public static extern global::System.IntPtr new_FeatureLocationResultWrapper();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_FeatureLocationResultWrapper___")]
  public static extern void delete_FeatureLocationResultWrapper(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AIDI__SWIG_0___")]
  public static extern global::System.IntPtr new_AIDI__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AIDI__SWIG_1___")]
  public static extern global::System.IntPtr new_AIDI__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AIDI___")]
  public static extern void delete_AIDI(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDI_set_param___")]
  public static extern void AIDI_set_param(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDI_initial_test_model___")]
  public static extern void AIDI_initial_test_model(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDI_set_batch_size___")]
  public static extern void AIDI_set_batch_size(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDI_set_detect_use_filter___")]
  public static extern void AIDI_set_detect_use_filter(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDI_start_test__SWIG_0___")]
  public static extern string AIDI_start_test__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDI_start_test__SWIG_1___")]
  public static extern global::System.IntPtr AIDI_start_test__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDI_start_test__SWIG_2___")]
  public static extern string AIDI_start_test__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AIDIEntrance___")]
  public static extern global::System.IntPtr new_AIDIEntrance();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AIDIEntrance___")]
  public static extern void delete_AIDIEntrance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDIEntrance_set_model_root___")]
  public static extern void AIDIEntrance_set_model_root(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDIEntrance_initialize__SWIG_0___")]
  public static extern void AIDIEntrance_initialize__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDIEntrance_initialize__SWIG_1___")]
  public static extern void AIDIEntrance_initialize__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AIDIEntrance_entrance_test_image___")]
  public static extern string AIDIEntrance_entrance_test_image(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiClassify__SWIG_0___")]
  public static extern global::System.IntPtr new_AidiClassify__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiClassify__SWIG_1___")]
  public static extern global::System.IntPtr new_AidiClassify__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AidiClassify___")]
  public static extern void delete_AidiClassify(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiClassify_set_param___")]
  public static extern void AidiClassify_set_param(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiClassify_initial_test_model___")]
  public static extern void AidiClassify_initial_test_model(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiClassify_start_test___")]
  public static extern int AidiClassify_start_test(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiLocation__SWIG_0___")]
  public static extern global::System.IntPtr new_AidiLocation__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiLocation__SWIG_1___")]
  public static extern global::System.IntPtr new_AidiLocation__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AidiLocation___")]
  public static extern void delete_AidiLocation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_set_test_data___")]
  public static extern void AidiLocation_set_test_data(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_set_param___")]
  public static extern bool AidiLocation_set_param(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_set_score_threshold___")]
  public static extern void AidiLocation_set_score_threshold(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_set_nms_threshold___")]
  public static extern void AidiLocation_set_nms_threshold(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_set_test_batches___")]
  public static extern void AidiLocation_set_test_batches(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_initialize_test_model___")]
  public static extern void AidiLocation_initialize_test_model(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_start_test___")]
  public static extern void AidiLocation_start_test(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiLocation_get_test_rect___")]
  public static extern global::System.IntPtr AidiLocation_get_test_rect(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiSegment__SWIG_0___")]
  public static extern global::System.IntPtr new_AidiSegment__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiSegment__SWIG_1___")]
  public static extern global::System.IntPtr new_AidiSegment__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AidiSegment___")]
  public static extern void delete_AidiSegment(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiSegment_set_param___")]
  public static extern void AidiSegment_set_param(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiSegment_initial_test_model___")]
  public static extern void AidiSegment_initial_test_model(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiSegment_set_threshold___")]
  public static extern void AidiSegment_set_threshold(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiSegment_set_filter_area___")]
  public static extern void AidiSegment_set_filter_area(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiSegment_set_filter_width___")]
  public static extern void AidiSegment_set_filter_width(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiSegment_set_filter_height___")]
  public static extern void AidiSegment_set_filter_height(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiSegment_start_test___")]
  public static extern global::System.IntPtr AidiSegment_start_test(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiCalculation___")]
  public static extern global::System.IntPtr new_AidiCalculation();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AidiCalculation___")]
  public static extern void delete_AidiCalculation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiCalculation_get_location_result__SWIG_0___")]
  public static extern global::System.IntPtr AidiCalculation_get_location_result__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiCalculation_get_location_result__SWIG_1___")]
  public static extern global::System.IntPtr AidiCalculation_get_location_result__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiCalculation_get_detect_result__SWIG_0___")]
  public static extern global::System.IntPtr AidiCalculation_get_detect_result__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiCalculation_get_detect_result__SWIG_1___")]
  public static extern global::System.IntPtr AidiCalculation_get_detect_result__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiCalculation_get_classify_result__SWIG_0___")]
  public static extern global::System.IntPtr AidiCalculation_get_classify_result__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiCalculation_get_classify_result__SWIG_1___")]
  public static extern global::System.IntPtr AidiCalculation_get_classify_result__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiCalculation_get_feature_location_result___")]
  public static extern global::System.IntPtr AidiCalculation_get_feature_location_result(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_new_AidiTools___")]
  public static extern global::System.IntPtr new_AidiTools();

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_delete_AidiTools___")]
  public static extern void delete_AidiTools(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("csharpaidiclient", EntryPoint="CSharp_AqrosefAidi_AidiTools_get_devices_number___")]
  public static extern int AidiTools_get_devices_number(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
