//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class DefectDetectResultWrapper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DefectDetectResultWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DefectDetectResultWrapper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DefectDetectResultWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_DefectDetectResultWrapper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public double recall {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_recall_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_recall_get(swigCPtr);
      return ret;
    } 
  }

  public double ap {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_ap_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_ap_get(swigCPtr);
      return ret;
    } 
  }

  public double center_recall {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_center_recall_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_center_recall_get(swigCPtr);
      return ret;
    } 
  }

  public double center_ap {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_center_ap_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_center_ap_get(swigCPtr);
      return ret;
    } 
  }

  public long all_gt_num {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_all_gt_num_set(swigCPtr, value);
    } 
    get {
      long ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_all_gt_num_get(swigCPtr);
      return ret;
    } 
  }

  public long recall_num {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_recall_num_set(swigCPtr, value);
    } 
    get {
      long ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_recall_num_get(swigCPtr);
      return ret;
    } 
  }

  public long all_center_num {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_all_center_num_set(swigCPtr, value);
    } 
    get {
      long ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_all_center_num_get(swigCPtr);
      return ret;
    } 
  }

  public long center_recall_num {
    set {
      csharpaidiclientPINVOKE.DefectDetectResultWrapper_center_recall_num_set(swigCPtr, value);
    } 
    get {
      long ret = csharpaidiclientPINVOKE.DefectDetectResultWrapper_center_recall_num_get(swigCPtr);
      return ret;
    } 
  }

  public DefectDetectResultWrapper() : this(csharpaidiclientPINVOKE.new_DefectDetectResultWrapper(), true) {
  }

}

}
