//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class FactoryClientParamWrapper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FactoryClientParamWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FactoryClientParamWrapper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FactoryClientParamWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_FactoryClientParamWrapper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public StringVector save_model_path_list {
    set {
      csharpaidiclientPINVOKE.FactoryClientParamWrapper_save_model_path_list_set(swigCPtr, StringVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = csharpaidiclientPINVOKE.FactoryClientParamWrapper_save_model_path_list_get(swigCPtr);
      StringVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector(cPtr, false);
      return ret;
    } 
  }

  public StringVector operator_name_list {
    set {
      csharpaidiclientPINVOKE.FactoryClientParamWrapper_operator_name_list_set(swigCPtr, StringVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = csharpaidiclientPINVOKE.FactoryClientParamWrapper_operator_name_list_get(swigCPtr);
      StringVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector(cPtr, false);
      return ret;
    } 
  }

  public StringVector operator_type_list {
    set {
      csharpaidiclientPINVOKE.FactoryClientParamWrapper_operator_type_list_set(swigCPtr, StringVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = csharpaidiclientPINVOKE.FactoryClientParamWrapper_operator_type_list_get(swigCPtr);
      StringVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector(cPtr, false);
      return ret;
    } 
  }

  public int device_number {
    set {
      csharpaidiclientPINVOKE.FactoryClientParamWrapper_device_number_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.FactoryClientParamWrapper_device_number_get(swigCPtr);
      return ret;
    } 
  }

  public bool use_gpu {
    set {
      csharpaidiclientPINVOKE.FactoryClientParamWrapper_use_gpu_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.FactoryClientParamWrapper_use_gpu_get(swigCPtr);
      return ret;
    } 
  }

  public bool use_runtime {
    set {
      csharpaidiclientPINVOKE.FactoryClientParamWrapper_use_runtime_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.FactoryClientParamWrapper_use_runtime_get(swigCPtr);
      return ret;
    } 
  }

  public FactoryClientParamWrapper() : this(csharpaidiclientPINVOKE.new_FactoryClientParamWrapper(), true) {
  }

}

}
