//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class FeatureLocationResultWrapper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FeatureLocationResultWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FeatureLocationResultWrapper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FeatureLocationResultWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_FeatureLocationResultWrapper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public double ap {
    set {
      csharpaidiclientPINVOKE.FeatureLocationResultWrapper_ap_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.FeatureLocationResultWrapper_ap_get(swigCPtr);
      return ret;
    } 
  }

  public double recall {
    set {
      csharpaidiclientPINVOKE.FeatureLocationResultWrapper_recall_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.FeatureLocationResultWrapper_recall_get(swigCPtr);
      return ret;
    } 
  }

  public double position_ap {
    set {
      csharpaidiclientPINVOKE.FeatureLocationResultWrapper_position_ap_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.FeatureLocationResultWrapper_position_ap_get(swigCPtr);
      return ret;
    } 
  }

  public double position_recall {
    set {
      csharpaidiclientPINVOKE.FeatureLocationResultWrapper_position_recall_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.FeatureLocationResultWrapper_position_recall_get(swigCPtr);
      return ret;
    } 
  }

  public FeatureLocationResultWrapper() : this(csharpaidiclientPINVOKE.new_FeatureLocationResultWrapper(), true) {
  }

}

}
