//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class LocationClientParamWrapper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LocationClientParamWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LocationClientParamWrapper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LocationClientParamWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_LocationClientParamWrapper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string model_path {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_model_path_set(swigCPtr, value);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_model_path_get(swigCPtr);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string deploy {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_deploy_set(swigCPtr, value);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_deploy_get(swigCPtr);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string save_model_path {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_save_model_path_set(swigCPtr, value);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_save_model_path_get(swigCPtr);
      if (csharpaidiclientPINVOKE.SWIGPendingException.Pending) throw csharpaidiclientPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool save_model_path_defined {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_save_model_path_defined_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_save_model_path_defined_get(swigCPtr);
      return ret;
    } 
  }

  public int test_input_shape_w {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_w_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_w_get(swigCPtr);
      return ret;
    } 
  }

  public int test_input_shape_h {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_h_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_h_get(swigCPtr);
      return ret;
    } 
  }

  public int test_input_shape_c {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_c_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_c_get(swigCPtr);
      return ret;
    } 
  }

  public int test_input_shape {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_test_input_shape_get(swigCPtr);
      return ret;
    } 
  }

  public int batch_size {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_batch_size_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_batch_size_get(swigCPtr);
      return ret;
    } 
  }

  public bool use_gpu {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_use_gpu_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_use_gpu_get(swigCPtr);
      return ret;
    } 
  }

  public int device_number {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_device_number_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_device_number_get(swigCPtr);
      return ret;
    } 
  }

  public bool test_model_initialized_ {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_test_model_initialized__set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_test_model_initialized__get(swigCPtr);
      return ret;
    } 
  }

  public bool long_detection {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_long_detection_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_long_detection_get(swigCPtr);
      return ret;
    } 
  }

  public int split {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_split_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_split_get(swigCPtr);
      return ret;
    } 
  }

  public int split_w {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_split_w_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_split_w_get(swigCPtr);
      return ret;
    } 
  }

  public int split_h {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_split_h_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_split_h_get(swigCPtr);
      return ret;
    } 
  }

  public bool encrypt {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_encrypt_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_encrypt_get(swigCPtr);
      return ret;
    } 
  }

  public bool use_runtime {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_use_runtime_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_use_runtime_get(swigCPtr);
      return ret;
    } 
  }

  public bool force_set_gpu {
    set {
      csharpaidiclientPINVOKE.LocationClientParamWrapper_force_set_gpu_set(swigCPtr, value);
    } 
    get {
      bool ret = csharpaidiclientPINVOKE.LocationClientParamWrapper_force_set_gpu_get(swigCPtr);
      return ret;
    } 
  }

  public LocationClientParamWrapper() : this(csharpaidiclientPINVOKE.new_LocationClientParamWrapper(), true) {
  }

}

}
