//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Aqrose.Aidi {

public class LocationResultWrapper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LocationResultWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LocationResultWrapper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LocationResultWrapper() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csharpaidiclientPINVOKE.delete_LocationResultWrapper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public double mAP {
    set {
      csharpaidiclientPINVOKE.LocationResultWrapper_mAP_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.LocationResultWrapper_mAP_get(swigCPtr);
      return ret;
    } 
  }

  public double recall {
    set {
      csharpaidiclientPINVOKE.LocationResultWrapper_recall_set(swigCPtr, value);
    } 
    get {
      double ret = csharpaidiclientPINVOKE.LocationResultWrapper_recall_get(swigCPtr);
      return ret;
    } 
  }

  public int all_gt_num {
    set {
      csharpaidiclientPINVOKE.LocationResultWrapper_all_gt_num_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationResultWrapper_all_gt_num_get(swigCPtr);
      return ret;
    } 
  }

  public int all_pred_num {
    set {
      csharpaidiclientPINVOKE.LocationResultWrapper_all_pred_num_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationResultWrapper_all_pred_num_get(swigCPtr);
      return ret;
    } 
  }

  public int recall_num {
    set {
      csharpaidiclientPINVOKE.LocationResultWrapper_recall_num_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationResultWrapper_recall_num_get(swigCPtr);
      return ret;
    } 
  }

  public int precise_num {
    set {
      csharpaidiclientPINVOKE.LocationResultWrapper_precise_num_set(swigCPtr, value);
    } 
    get {
      int ret = csharpaidiclientPINVOKE.LocationResultWrapper_precise_num_get(swigCPtr);
      return ret;
    } 
  }

  public LocationResultWrapper() : this(csharpaidiclientPINVOKE.new_LocationResultWrapper(), true) {
  }

}

}
